### ISSUE TITLE
Not working with php 7.4

### ISSUE THREAD

**Issue by LavBhelloriya** [7kmCo/wp-redisearch#1]
This plugin seems to have issues with php version 7.4 and above. Please make it compatible. Thanks!!

**Comment by foadyousefi** [comment]
Thanks for using this plugin and reporting and sorry for the delay in answering.

I just upgraded my PHP version to 7.4.2 and tested the functionality. I'm not able to reproduce any issue.

Can you describe your issues bit more precise please?

**Comment by foadyousefi** [comment]
Since no response, closing.
