### ISSUE TITLE
RediSearch module not loaded! go to settings

### ISSUE THREAD

**Issue by jmartincufre** [7kmCo/wp-redisearch#9]
Hello, I'm seeing this error and looks strange, because I also have another site with the same configuration and it is working fine! 

Using docker, php 7.4, and redisearch docker image redislabs/redisearch:latest - Also tryed with another redisearch image, with no success. Looks like its a PHP or plugin issue. Could you give me a hand on this?

**Comment by jmartincufre** [comment]
Hello again! I figured out that the issue is caused by the Redisearch module version. Your plugin is working up to version 1.8.6 -

**Comment by foadyousefi** [comment]
Thanks for reporting. I was working on the PHP package communicating with [RediSearch](https://github.com/front/redisearch) server to implement RediSearch version 2.0. Will do the upgrade for this plugin in coming days.
